### ISSUE TITLE
Assertion error in client.prinipal

### ISSUE THREAD

**Issue by frank-pet** [python-caldav/caldav#136]
On master  0.8.0rc0 downloaded from github on 2/8/2021

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/MessageBoard/dev/caldav/davclient.py", line 319, in principal
    return Principal(self)
  File "/home/pi/MessageBoard/dev/caldav/objects.py", line 398, in __init__
    cup = self.get_properties([dav.CurrentUserPrincipal()])
  File "/home/pi/MessageBoard/dev/caldav/objects.py", line 221, in get_properties
    properties = self._handle_xml_response(response, props)
  File "/home/pi/MessageBoard/dev/caldav/objects.py", line 192, in _handle_xml_response
    results = response.expand_simple_props(props=props, multi_value_props=multi_value_props)
  File "/home/pi/MessageBoard/dev/caldav/davclient.py", line 241, in expand_simple_props
    self.find_objects_and_props()
  File "/home/pi/MessageBoard/dev/caldav/davclient.py", line 177, in find_objects_and_props
    error.assert_(not href in self.objects)
  File "/home/pi/MessageBoard/dev/caldav/lib/error.py", line 23, in assert_
    assert(condition)
AssertionError

Note.  Commented out the assertion on line 177 and everything seemed to work fine.

Log files attached.
[example1.log](https://github.com/python-caldav/caldav/files/5945818/example1.log)

**Comment by tobixen** [comment]
The reply from the server contains two hrefs (one directly in the response block, the other nested inside the propstat/prop blocks), that's probably what's triggering the assert.  I've seen similar things from iCloud.  I have no clue if this is a breach of the standard or not, but I'll make some unit test and make sure that this XML does not cause any asserts to be triggered.

PS: in the current master branch, it's possible to set an environment variable PYTHON_CALDAV_DEBUG_MODE.  If it's set to DEBUG_PDB, one will be thrown into the debugger when asserts are raised.  If set to PRODUCTION, the asserts will log errors rather than break everything.

**Comment by tobixen** [comment]
Oh, when doing more research on it, I can see that the URL is actually repeated three times in the returned XML.  The response block is actually duplicated.  Anyway ... as long as there exists caldav servers giving such a response, we should not throw an AssertionError.  I've remade the code into accepting duplicates.
