### ISSUE TITLE
AttributeError: module 'caldav' has no attribute 'DAVClient'

### ISSUE THREAD

**Issue by mh-g** [python-caldav/caldav#139]
Using Python 3.7 on Raspbian 10 and a new virtual environment containing only caldav
```
user@mediaberry:~/PycharmProjects/calendar $ python3 -m venv venv
user@mediaberry:~/PycharmProjects/calendar $ source venv/bin/activate
(venv) user@mediaberry:~/PycharmProjects/calendar $ pip3 install caldav
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting caldav
  Using cached https://files.pythonhosted.org/packages/be/fd/cdc3a42712cdef6ba8ee5ae547c61bce15d3230459a339ced24431d4aab2/caldav-0.7.1-py3-none-any.whl
Collecting six (from caldav)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting lxml (from caldav)
  Using cached https://www.piwheels.org/simple/lxml/lxml-4.6.2-cp37-cp37m-linux_armv7l.whl
Collecting requests (from caldav)
  Using cached https://files.pythonhosted.org/packages/29/c1/24814557f1d22c56d50280771a17307e6bf87b70727d975fd6b2ce6b014a/requests-2.25.1-py2.py3-none-any.whl
Collecting vobject (from caldav)
  Using cached https://www.piwheels.org/simple/vobject/vobject-0.9.6.1-py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->caldav)
  Using cached https://files.pythonhosted.org/packages/5e/a0/5f06e1e1d463903cf0c0eebeb751791119ed7a4b3737fdc9a77f1cdfb51f/certifi-2020.12.5-py2.py3-none-any.whl
Collecting chardet<5,>=3.0.2 (from requests->caldav)
  Using cached https://files.pythonhosted.org/packages/19/c7/fa589626997dd07bd87d9269342ccb74b1720384a4d739a1872bd84fbe68/chardet-4.0.0-py2.py3-none-any.whl
Collecting urllib3<1.27,>=1.21.1 (from requests->caldav)
  Using cached https://files.pythonhosted.org/packages/23/fc/8a49991f7905261f9ca9df5aa9b58363c3c821ce3e7f671895442b7100f2/urllib3-1.26.3-py2.py3-none-any.whl
Collecting idna<3,>=2.5 (from requests->caldav)
  Using cached https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl
Collecting python-dateutil>=2.4.0 (from vobject->caldav)
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Installing collected packages: six, lxml, certifi, chardet, urllib3, idna, requests, python-dateutil, vobject, caldav
Successfully installed caldav-0.7.1 certifi-2020.12.5 chardet-4.0.0 idna-2.10 lxml-4.6.2 python-dateutil-2.8.1 requests-2.25.1 six-1.15.0 urllib3-1.26.3 vobject-0.9.6.1
```
and a very minimal sample program calendar.py:
```
import caldav
client = caldav.DAVClient()
```
I get the following error:
```
(venv) user@mediaberry:~/PycharmProjects/calendar $ python3 calendar.py 
Traceback (most recent call last):
  File "calendar.py", line 1, in <module>
    import caldav
  File "/home/user/PycharmProjects/calendar/venv/lib/python3.7/site-packages/caldav/__init__.py", line 3, in <module>
    from .davclient import DAVClient
  File "/home/user/PycharmProjects/calendar/venv/lib/python3.7/site-packages/caldav/davclient.py", line 6, in <module>
    import requests
  File "/home/user/PycharmProjects/calendar/venv/lib/python3.7/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/user/PycharmProjects/calendar/venv/lib/python3.7/site-packages/urllib3/__init__.py", line 11, in <module>
    from . import exceptions
  File "/home/user/PycharmProjects/calendar/venv/lib/python3.7/site-packages/urllib3/exceptions.py", line 3, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/user/PycharmProjects/calendar/venv/lib/python3.7/site-packages/urllib3/packages/six.py", line 199, in load_module
    mod = mod._resolve()
  File "/home/user/PycharmProjects/calendar/venv/lib/python3.7/site-packages/urllib3/packages/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/home/user/PycharmProjects/calendar/venv/lib/python3.7/site-packages/urllib3/packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python3.7/http/client.py", line 71, in <module>
    import email.parser
  File "/usr/lib/python3.7/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/usr/lib/python3.7/email/feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "/usr/lib/python3.7/email/_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "/usr/lib/python3.7/email/utils.py", line 33, in <module>
    from email._parseaddr import quote
  File "/usr/lib/python3.7/email/_parseaddr.py", line 16, in <module>
    import time, calendar
  File "/home/user/PycharmProjects/calendar/calendar.py", line 3, in <module>
    client = caldav.DAVClient()
AttributeError: module 'caldav' has no attribute 'DAVClient'
```

**Comment by tobixen** [comment]
This is most likely a duplicate. Make sure your own file is not named caldav, or not in the python library path.

**Comment by mh-g** [comment]
Thanks for the suggestion. I did a `sudo find / -name *caldav* -print` but there are no other relevant files with such names (only a few caldav.php files in the calender storage of Radicale.

**Comment by tobixen** [comment]
Interesting.  Please do this and report back:

```python
import caldav
caldav.__file__
```

**Comment by tobixen** [comment]
The traceback is kind of weird.  Hm.  Ah, I see!  Rename your file to something else than calendar.py.

This is silly ... but not an issue with the caldav library per se.  Through an entaglement of dependencies,  `email.parser` is imported, this one is again trying to import `calendar`, and then it's trying to import your file.  Since it's doing this while it's still importing the caldav library, caldav.DAVClient does not exist yet.

**Comment by tobixen** [comment]
Putting your code into a subroutine (i.e. following the pattern described at https://realpython.com/python-main-function/) would probably also cause this traceback to disappear, but there may be dragons as it then still has imported the wrong "calendar".

The calendar module is a built-in in python, so from that point of view it's bad practice to name files calendar.py.

**Comment by mh-g** [comment]
Thanks a lot, just renaming the file helped!
