### ISSUE TITLE
[SOGo]  Deviation from expectations found.  Please raise an issue ...

### ISSUE THREAD

**Issue by andreas-amlabs** [python-caldav/caldav#184]
Recently switched from Baikal to SOGo Groupware for email, calendar and carddav. Today I switched HomeAssistant
to use the SOGo calendar and found this issue (below)

The installation is a locally hosted mailcow docker setup, https://hub.docker.com/r/mailcow/sogo
Homeassistant is running version 2022.2.9

URI being access is setup in HA like

calendar:
  - platform: caldav
    username: user@example.com
    password: !secret user_sogo
    url: "http://example.com/SOGo/dav/user@example.se/Calendar/personal/"

Reported here as per error request.

2022-05-08 20:10:55 ERROR (SyncWorker_5) [caldav] Deviation from expectations found.  Please raise an issue at https://github.com/python-caldav/caldav/issues or reach out to t-caldav@tobixen.no, include this error and the traceback and tell what server you are using
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/caldav/lib/error.py", line 25, in assert_
    assert(condition)
AssertionError
2022-05-08 20:10:55 ERROR (SyncWorker_5) [caldav] Deviation from expectations found.  Please raise an issue at https://github.com/python-caldav/caldav/issues or reach out to t-caldav@tobixen.no, include this error and the traceback and tell what server you are using
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/caldav/lib/error.py", line 25, in assert_
    assert(condition)
AssertionError
2022-05-08 20:10:55 ERROR (MainThread) [homeassistant.components.calendar] Error while setting up caldav platform for calendar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/caldav/calendar.py", line 87, in setup_platform
    calendars = client.principal().calendars()
  File "/usr/local/lib/python3.9/site-packages/caldav/davclient.py", line 350, in principal
    self._principal = Principal(client=self, *largs, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/caldav/objects.py", line 399, in __init__
    cup = self.get_property(dav.CurrentUserPrincipal())
  File "/usr/local/lib/python3.9/site-packages/caldav/objects.py", line 174, in get_property
    foo = self.get_properties([prop], **passthrough)
  File "/usr/local/lib/python3.9/site-packages/caldav/objects.py", line 204, in get_properties
    properties = response.expand_simple_props(props)
  File "/usr/local/lib/python3.9/site-packages/caldav/davclient.py", line 265, in expand_simple_props
    self.find_objects_and_props()
  File "/usr/local/lib/python3.9/site-packages/caldav/davclient.py", line 190, in find_objects_and_props
    responses = self._strip_to_multistatus()
  File "/usr/local/lib/python3.9/site-packages/caldav/davclient.py", line 128, in _strip_to_multistatus
    if (tree.tag == 'xml' and tree[0].tag == dav.MultiStatus.tag):
AttributeError: 'NoneType' object has no attribute 'tag'

On an unclear side note I would like to mention that the error gets reduced to

2022-05-08 20:24:03 ERROR (SyncWorker_1) [caldav] Deviation from expectations found.  Please raise an issue at https://github.com/python-caldav/caldav/issues or reach out to t-caldav@tobixen.no, include this error and the traceback and tell what server you are using
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/caldav/lib/error.py", line 25, in assert_
    assert(condition)
AssertionError

when using https instead of http. However http is 301 redirected in nginx to https (which acts as certificate proxy for the sogo setup)
I would have expected the same error output in both cases ! :)

**Comment by tobixen** [comment]
- HomeAssistant 2022.2.9 is using caldav 0.8.2, unfortunately caldav 0.8.2 have proven to fail towards some calendar servers.  I would like you to try caldav 0.9 if that's possible, hopefully all problems will disappear with 0.9.  Latest build of HomeAssistant (to be released in June I hope) is based on 0.9.  It's also possible to do some hand patching inside the docker container.
- The first traceback is unfortunately useless - I was under the impression that the full traceback would be logged, perhaps something have changed ... or perhaps I have to read up on how to log a proper traceback.
- The second traceback ... some XML is expected from the server, but apparently no content given.  It may be related to the problems with 0.8.2.

Unfortunately I did not do any testing towards SOGo prior to releasing 0.9 though.  It would be nice to do automated testing towards SOGo, but I haven't had time to look into that.

**Comment by andreas-amlabs** [comment]
Thanks !

I will upgrade during the week and report back to you !

**Comment by the-glu** [comment]
Hello,

SOGo user of the lib in another project here, I do confirm I did have the issue before upgrading to 0.9.0. Now it does seem to works :)

And I only go the same short trackback (so I never investigated) (and I'm using HTTPs).

**Comment by andreas-amlabs** [comment]
Sorry for not reporting back, got sick and then forgot. Right now
I am waiting for HA 2022.6 to be released, which contains version 0.9

**Comment by andreas-amlabs** [comment]
Hi

On Home Assistant 2022.6.6 this issue seems to no longer be there
