### ISSUE TITLE
Module not found error - "recurring_ical_events"

### ISSUE THREAD

**Issue by lothar-mar** [python-caldav/caldav#329]
As mentioned in the title, i get this error when running "test_caldav.py" and "test_caldav_unit.py":

```
FAILED tests/test_caldav.py::TestLocalRadicale::testTodoDatesearch - ModuleNotFoundError: No module named 'recurring_ical_events'
FAILED tests/test_caldav.py::TestLocalRadicale::testRecurringDateSearch - ModuleNotFoundError: No module named 'recurring_ical_events'
FAILED tests/test_caldav_unit.py::TestExpandRRule::testZero - ModuleNotFoundError: No module named 'recurring_ical_events'
FAILED tests/test_caldav_unit.py::TestExpandRRule::testOne - ModuleNotFoundError: No module named 'recurring_ical_events'
FAILED tests/test_caldav_unit.py::TestExpandRRule::testThree - ModuleNotFoundError: No module named 'recurring_ical_events'
FAILED tests/test_caldav_unit.py::TestExpandRRule::testThreeTodo - ModuleNotFoundError: No module named 'recurring_ical_events'
FAILED tests/test_caldav_unit.py::TestExpandRRule::testSplit - ModuleNotFoundError: No module named 'recurring_ical_events'
FAILED tests/test_caldav_unit.py::TestExpandRRule::test241 - ModuleNotFoundError: No module named 'recurring_ical_events'
```

AM I missing some dependencies perhaps?

**Comment by tobixen** [comment]
Yes, `recurring-ical-events` is listed as dependency in setup.py.

**Comment by daniele-athome** [comment]
I'll take the liberty of recycling this issue because the title of my bug would be the identical :-)

```
Traceback (most recent call last):
   File "/home/homeassistant/hass/lib/python3.13/site-packages/homeassistant/helpers/update_coordinator.py>
     self.data = await self._async_update_data()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/homeassistant/hass/lib/python3.13/site-packages/homeassistant/components/caldav/coordinator>
     results = await self.hass.async_add_executor_job(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     ...<7 lines>...
     )
     ^
   File "/usr/lib/python3.13/concurrent/futures/thread.py", line 59, in run
     result = self.fn(*self.args, **self.kwargs)
   File "/home/homeassistant/hass/lib/python3.13/site-packages/caldav/objects.py", line 1105, in search
     o.expand_rrule(start, end)
     ~~~~~~~~~~~~~~^^^^^^^^^^^^
   File "/home/homeassistant/hass/lib/python3.13/site-packages/caldav/objects.py", line 1796, in expand_rr>
     import recurring_ical_events
 ModuleNotFoundError: No module named 'recurring_ical_events'
```

This is happening in Home Assistant, caldav integration, with both python-caldav 1.3.9 and 1.4.0. I'm guessing it has something to do with this item [in this changelog](https://github.com/niccokunzmann/python-recurring-ical-events?tab=readme-ov-file#changelog):

> Restructure module into package with a file structure.

That is, the directory `recurring_ical_events` doesn't exist anymore in my Python installation - I'm not really sure what is happening here though.

**Comment by tobixen** [comment]
Ouch.  Which version of the `recurring_ical_events` is used in your homeassistant installation?

**Comment by daniele-athome** [comment]
The latest, version 3.5.0.

**Comment by tobixen** [comment]
3.5.0 was released yesterday.  I'll try and run the test code and see if I can reproduce it locally

**Comment by tobixen** [comment]
That would surprise me, @niccokunzmann seems to be pretty clever at such things.

**Comment by tobixen** [comment]
I didn't check 3.5.0 specifically, but with the HEAD of the master branch at my laptop, there are no problems running the caldav test code.

**Comment by tobixen** [comment]
In the "classic" system-wide configuration I wasn't able to reproduce, and using venv all caldav tests passed - but the `recurring_ical_events` is lazily loaded when needed rather than immediately when loading the caldav library, the tests are probably running only towards xandikos on a plain venv, xandikos does not support recurrences, hence all tests involving recurrences are skipped.  I can indeed reproduce the issue, being unable to load `recurring_ical_events` from a plain venv.  

And yes, since the bug is reproducible without involving the caldav library, it would be more approriate to file it under the `recurring_ical_event` project :-) https://github.com/niccokunzmann/python-recurring-ical-events

**Comment by daniele-athome** [comment]
Thanks for the support! Opened niccokunzmann/python-recurring-ical-events#214

**Comment by niccokunzmann** [comment]
Sorry for the inconvenience! I will delete the release once there is a fix. Then, you do not need to add an exception.
