### ISSUE TITLE
Imports not working?

### ISSUE THREAD

**Issue by mattelacchiato** [python-caldav/caldav#51]
Hi,

I'm not sure if I'm doing something completely wrong, but I can't get this lib working. I've copied the example from [the docs](https://pythonhosted.org/caldav/) and still failing at the imports...
```
$ python -V
Python 2.7.15
$ pip list
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Package         Version 
--------------- --------
caldav          0.6.0   
certifi         2019.3.9
chardet         3.0.4   
idna            2.8     
lxml            4.3.3   
pip             19.0.3  
python-dateutil 2.8.0   
pytz            2018.9  
requests        2.21.0  
setuptools      40.8.0  
six             1.12.0  
tzlocal         1.5.1   
urllib3         1.24.1  
vobject         0.9.6.1 
wheel           0.33.1  
$ python caldav.py 
Traceback (most recent call last):
  File "caldav.py", line 2, in <module>
    import caldav
  File "/home/mb/projects/inoio/sogo-connector/caldav.py", line 3, in <module>
    from caldav.elements import dav, cdav
ImportError: No module named elements
```
What am I missing?

**Comment by mattelacchiato** [comment]
Nevermind, I've named my file "caldav.py" :man_facepalming:
