### ISSUE TITLE
KeyError: exception_by_method['proppach']  

### ISSUE THREAD

**Issue by dz0** [python-caldav/caldav#54]
Repetitevely running example from Quickstart https://pythonhosted.org/caldav/#quickstart
I got Error:

```
Renaming
Traceback (most recent call last):
  File "caldav_demo.py", line 34, in <module>
    calendar.set_properties([dav.DisplayName("Test calendar"),])
  File "caldav/objects.py", line 250, in set_properties
    r = self._query(root, query_method='proppatch')
  File "caldav/objects.py", line 167, in _query
    raise error.exception_by_method[query_method](errmsg(ret))
KeyError: 'proppatch'
```
caldav 0.6.1
py: 3.5

*** I suspect `proppatch` is related to `propset` here

**Comment by tobixen** [comment]
Sorry for the slow response.

The doc seems to be slightly outdated, I should look into that.  Still, the code should work.

Changing the display name of the calendar may fail, dependent on what calendar server you're using and what permissions you have on said calendar.  However, the error message ought to be clear and obviously it's a bug that we get an exception in the exception handling.  I'll try to fix that, make a separate issue that the documentation should be refreshed and when done I'll close this issue.
