### ISSUE TITLE
module caldav has no attribute DAVClient

### ISSUE THREAD

**Issue by dukeofcool199** [python-caldav/caldav#74]
i keep recieiving an error that the caldav module has no DAVClient attribute.
i based my code off of the sample code found in the documentation  
```self.client = caldav.DAVClient(self.url)``` 
`self.principal = self.client.principal()`

here is the stack trace

```Traceback (most recent call last):
  File "calendar.py", line 2, in <module>
    from caldav.elements import dav, cdav, base
  File "/home/jenkin/.local/lib/python3.7/site-packages/caldav/__init__.py", line 3, in <module>
    from .davclient import DAVClient
  File "/home/jenkin/.local/lib/python3.7/site-packages/caldav/davclient.py", line 6, in <module>
    import requests
  File "/usr/lib/python3.7/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3.7/site-packages/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import (
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/usr/lib/python3.7/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/lib/python3.7/site-packages/urllib3/packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/usr/lib/python3.7/site-packages/urllib3/packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python3.7/site-packages/urllib3/packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python3.7/http/client.py", line 71, in <module>
    import email.parser
  File "/usr/lib/python3.7/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/usr/lib/python3.7/email/feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "/usr/lib/python3.7/email/_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "/usr/lib/python3.7/email/utils.py", line 33, in <module>
    from email._parseaddr import quote
  File "/usr/lib/python3.7/email/_parseaddr.py", line 16, in <module>
    import time, calendar
  File "/home/jenkin/workspace/moms_calendar_python/calendar.py", line 55, in <module>
    cal = EventsCalendar()
  File "/home/jenkin/workspace/moms_calendar_python/calendar.py", line 9, in __init__
    self.setup_client() 
  File "/home/jenkin/workspace/moms_calendar_python/calendar.py", line 16, in setup_client
    self.client = caldav.DAVClient(self.url) 
AttributeError: module 'caldav' has no attribute 'DAVClient'```

**Comment by tobixen** [comment]
Seems like a namespace conflict.  Try renaming your file from calendar.py to something else.

(caldav depends on requests, requests depends on http.client, apparently http.client depends on email.parser - that's weird to me - email.parser depends on a calendar module, when it tries importing it, it finds your calendar.py instead.  I believe things then break because caldav.DAVClient hasn't been set up yet)

**Comment by dukeofcool199** [comment]
that seems to have worked.  thank you very much for the quick assistance.
