### ISSUE TITLE
vobject.base.ParseError: At line 1: Component [VCALENDAR OBJECT] was never closed

### ISSUE THREAD

**Issue by thelouisvivier** [python-caldav/caldav#80]
Hey !

I am trying to automate my calendar with a small script in python. 
I could connect to my Caldav server (on a Synology NAS), I could fetch events, I can rename the calendar, but I can't add a new one. 
I am getting this error :

```
Traceback (most recent call last):
  File "aurionfetcher.py", line 50, in <module>
    aurion.syncCaldav()
  File "/home/louis/aurionfetcher/aurion.py", line 270, in syncCaldav
    event = calendar.add_event(ev1)
  File "/usr/local/lib/python3.6/dist-packages/caldav/objects.py", line 508, in add_event
    return Event(self.client, data=ical, parent=self).save()
  File "/usr/local/lib/python3.6/dist-packages/caldav/objects.py", line 963, in save
    self._create(self._data, self.id, path)
  File "/usr/local/lib/python3.6/dist-packages/caldav/objects.py", line 912, in _create
    if hasattr(self.vobject_instance, obj_type):
  File "/usr/local/lib/python3.6/dist-packages/caldav/objects.py", line 995, in _get_vobject_instance
    self._vobject_instance = vobject.readOne(to_unicode(self._data))
  File "/usr/local/lib/python3.6/dist-packages/vobject/base.py", line 1156, in readOne
    allowQP))
  File "/usr/local/lib/python3.6/dist-packages/vobject/base.py", line 1142, in readComponents
    (stack.topName())), n)
vobject.base.ParseError: At line 1: Component VCALENDAR       PRODID:-//SYNOLOGY//EN       VERSION:2.0       BEGIN:VEVENT       CREATED:20191107T212248       LAST-MODIFIED:20191107T212248       DTSTAMP:20191107T212248       UID:20191107T212248-DD5A2BC4@172.17.0.1       SEQUENCE:1       SUMMARY:TEST       TRANSP:TRANSPARENT       DTSTART;VALUE=DATE:20191107       DTEND;VALUE=DATE:20191108       DESCRIPTION:       LOCATION:       END:VEVENT       END:VCALENDAR        was never closed
```

I am using the code example from the documentation so I don't understand this error. I tried a lot of search on internet, but can't find a similar issue. 

I am using python 3, and Caldav is in version 0.6.1.

What am I doing wrong ?

Thank you for your help !

Here my full code : 

```python
ev1 = """BEGIN:VCALENDAR
        PRODID:-//Synology//EN
        VERSION:2.0
        BEGIN:VEVENT
        CREATED:20191107T212248
        LAST-MODIFIED:20191107T212248
        DTSTAMP:20191107T212248
        UID:20191107T212248-dd5a2bc4@172.17.0.1
        SEQUENCE:1
        SUMMARY:TEST
        TRANSP:TRANSPARENT
        DTSTART;VALUE=DATE:20191107
        DTEND;VALUE=DATE:20191108
        DESCRIPTION:
        LOCATION:
        END:VEVENT
        END:VCALENDAR
        """

        client = caldav.DAVClient(url=self._calurl, username=self._caluser, password=self._calpass)
        principal = client.principal()
        calendars = principal.calendars()
        if len(calendars) > 0:
            calendar = calendars[0]
            print ("Using calendar", calendar)
            print ("Renaming")
            calendar.set_properties([dav.DisplayName("Test calendar"),])
            print (calendar.get_properties([dav.DisplayName(),]))
            event = calendar.add_event(ev1)
            print ("Event", event, "created")
            print ("Looking for events in 2019-11")
            results = calendar.date_search(
                datetime(2019,11, 1), datetime(2019, 12, 1))
            for event in results:
                print ("Found", event)
```

**Comment by thelouisvivier** [comment]
After a lot of search, I found that you need to write your event without indenting...
Hope it will help someone !

**Comment by footgear404** [comment]
Thts mean this  - ev1 = """BEGIN:VCALENDAR
        PRODID:-//Synology//EN
        VERSION:2.0
        BEGIN:VEVENT
        CREATED:20191107T212248
        LAST-MODIFIED:20191107T212248
        DTSTAMP:20191107T212248
        UID:20191107T212248-dd5a2bc4@172.17.0.1
        SEQUENCE:1
        SUMMARY:TEST
        TRANSP:TRANSPARENT
        DTSTART;VALUE=DATE:20191107
        DTEND;VALUE=DATE:20191108
        DESCRIPTION:
        LOCATION:
        END:VEVENT
        END:VCALENDAR
        """ 
Change to this: 
"""BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Example Corp.//CalDAV Client//EN
BEGIN:VEVENT
UID:20200516T060000Z-123401@example.com
DTSTAMP:20200516T060000Z
DTSTART:20200517T060000Z
DTEND:20200517T230000Z
RRULE:FREQ=YEARLY
SUMMARY:Do the needful
END:VEVENT
END:VCALENDAR
"""
